### ISSUE TITLE
datasets数据打开是乱码

### ISSUE THREAD

**Issue by onetance** [Ee1s/NirGNN#3]
你好，我对您的这篇论文非常感兴趣。我想看一下datasets里的数据集，电脑系统是win11，可是尝试用pycharm、记事本和notepad++打开都是乱码。最后我用sublime打开貌似成功了，您可以帮我看看数据的格式打开是正确的吗。如果是错误的，请问您可以给我一些建议吗。十分感谢！
![image](https://github.com/Ee1s/NirGNN/assets/61740950/3f4b441c-d088-4baa-847b-00c6044701be)

**Comment by Ee1s** [comment]
您好，
数据集是编码过的，可以使用pickle.load 函数读取，例如在main.py中train_data = pickle.load(open('../datasets/' + opt.dataset + '/train.txt', 'rb'))
读取后在内存中的状态如下：
![image](https://github.com/Ee1s/NirGNN/assets/10851438/202b3244-d157-466f-ba14-139eddb48167)

**Comment by onetance** [comment]
十分感谢您的回复，您的回复对我的帮助非常大！
