### ISSUE TITLE
关于复现结果差

### ISSUE THREAD

**Issue by suke6577** [Ee1s/NirGNN#7]
你好，我对你的代码使用yelpsmall数据集MRR@20和MRR@10复现效果差0.1

**Comment by Ee1s** [comment]
> 你好，我对你的代码使用yelpsmall数据集MRR@20和MRR@10复现效果差0.1

请提供实验设备参数和模型超参数

**Comment by Ee1s** [comment]
Since there is no further update, I'll close this issue. Please feel free to reopen it if needed.
